import Link from "next/link";

export default function Preambule() {
  return (
    <div>
      • Preambuła : 1. CELEM ZWIĄZKU JEST: OBRONA GODNOŚCI, PRAW PRACUJĄCYCH ,
      INTERESÓW MATERIALNYCH I SOCJALNO- KULTUROWYCH, EMERYTÓW I RENCISTÓW,
      BEZROBOTNYCH I ICH RODZIN ORAZ INNYCH PODMIOTÓW ZWIĄZANYCH Z ROLNICTWEM.
      2. STAŁE REPREZENTOWANIE POTRZEB ORAZ OBRONĘ INTERESÓW CZŁONKÓW ZWIĄZKU
      WOBEC ORGANÓW WŁADZY SZEROKO ROZUMIANEJ I GOSPODARKI POPRZEZ: A) DĄŻENIE
      DO ZAKAZU WSZELKIEJ DYSKRYMINACJI I MOBBINGU W STOSUNKACH PRACY,
      SPRAWIEDLIWE TRAKTOWANIA PRACUJĄCYCH ZE STRONY PRACODAWCÓW, ADMINISTRACJI
      RZĄDOWEJ I SAMORZĄDU TERYTORIALNEGO, ŚRODKI MASOWEGO PRZEKAZU ORAZ RÓŻNYCH
      ORGANIZACJI I INSTYTUCJI, B) PRZEDKŁADANIE WNIOSKÓW, OPINII, ŻĄDAŃ NASZYCH
      CZŁONKÓW W KWESTII CEN PRODUKTÓW ROLNYCH, CEN I ŚRODKÓW DO PRODUKCJI
      ROLNEJ, ZASAD SYSTEMU ZBYTU PRODUKTÓW ROLNYCH, POLITYKĘ KREDYTOWĄ,
      PODATKOWĄ, KULTURALNOOŚWIATOWĄ I SOCJALNĄ, ŚWIADCZENIA EMERYTALNYCH
      ROLNIKÓW, ZAKUPU ZIEMI I JEJ SPRZEDAŻY, PRZEKAZANIU, DAROWANIU, C)
      INICJOWANIE, OPINIOWANIE I WSPÓŁUCZESTNICZENIE W OPRACOWYWANIU PROJEKTÓW
      AKTÓW PRAWNYCH Z TEGO ZAKRESU W ODNIESIENIU DO WSI, GMINY, POWIATU,
      WOJEWÓDZTWA, KRAJU . 3. PODEJMOWANIE INTERWENCJI LUB REPREZENTOWANIE
      CZŁONKÓW W INDYWIDUALNYCH SPRAWACH CZŁONKÓW ZWIĄZKU ORAZ W PRZYPADKU ICH
      PRZEWLEKŁEGO LUB KRZYWDZĄCEGO ZAŁATWIANIA POPRZEZ ORGANY DO TEGO POWOŁANE.
      4. BEZPOŚREDNIE ODDZIAŁYWANIE NA ROZWÓJ SPOŁECZNO-GOSPODARCZY REGIONU
      POPRZEZ SWOICH PRZEDSTAWICIELI WYBRANYCH DO LOKALNYCH ORGANÓW
      SAMORZĄDOWYCH, SEJMU, SENATU, EUROPARLAMENTU. 5. REPREZENTOWANIE I OBRONA
      INTERESÓW SPOŁECZNO-ZAWODOWYCH CZŁONKÓW Strona 4 z 6 ZWIĄZKU WOBEC ORGANÓW
      ADMINISTRACJI RZĄDOWEJ I SAMORZĄDOWEJ A TAKŻE INSTYTUCJI I ORGANIZACJI
      OBSŁUGUJĄCYCH WIEŚ I ROLNICTWO. 6. WSPÓŁDZIAŁANIE Z ORGANAMI WŁADZY I
      ADMINISTRACJI PAŃSTWOWEJ ORAZ PAŃSTWOWYMI I SPOŁECZNYMI JEDNOSTKAMI
      ORGANIZACYJNYMI OBSŁUGI ROLNICTWA I WSI W ISTOTNYCH SPRAWACH
      SPOŁECZNO-GOSPODARCZYCH I OŚWIATOWO-KULTURALNYCH. 5. WSPÓŁDZIAŁANIE Z IZBĄ
      ROLNICZĄ, ZWIĄZKAMI ROLNICZYCH ZRZESZEŃ BRANŻOWYCH, PARTIĄ I INNYMI
      PODMIOTAMI WE WSPÓLNYM REPREZENTOWANIU INTERESÓW CZŁONKÓW ZWIĄZKU,
      ROLNIKÓW INDYWIDUALNYCH I MIESZKAŃCÓW WSI I MIAST NIE BĘDĄCYMI CZŁONKAMI
      ZWIĄZKU . 6. UDZIELANIE POMOCY INSTRUKTAŻOWEJ I ORGANIZACYJNEJ, A W MIARĘ
      MOŻLIWOŚCI MATERIALNEJ ORGANIZACJOM W TYM MŁODZIEŻOWYM, PODMIOTOM, OSOBOM
      I INNYM WSPÓŁPRACUJĄCYM Z ZZRPWIS. 7. ZZRPWIS MOŻE UCZESTNICZYĆ W
      ORGANIZOWANIU WYPOCZYNKU WAKACYJNEGO DZIECI I MŁODZIEŻY, ROZWOJU SPORTU,
      TURYSTYKI, REKREACJI I DZIAŁALNOŚCI KULTURALNEJ NA WSI I W MIASTACH W
      KRAJU JAK I ZA GRANICĄ 8. WSPÓŁPRACOWAĆ ZE WSZELKIMI PODMIOTAMI
      ORGANIZACJAMI, STOWARZYSZENIAMI, ZWIĄZKAMI W KRAJU JAKI I UE W CELU
      OSIĄGNIĘCIA CELÓW ZWIĄZKU I ZAKŁADAĆ ODDZIAŁY WŁASNE W KRAJACH UE. 9.
      REPREZENTOWANIE I OBRONA INTERESÓW PRACOWNICZYCH NA FORUM MIĘDZYNARODOWYM.
    </div>
  );
}
